language: java

sudo: true

script:
 mvn verify

jdk:
 - oraclejdk8 

deploy:
   edge: true
   provider: cloudfoundry
   username: madhanswamy17@gmail.com
   password: sapphire.17
   api: https://api.run.pivotal.io
   organization: devchamps
   space: development


notifications:
  email:
    - madhan.packiriswamy@verizon.com
