language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

sudo: false

install: mvn install -Dgpg.skip=true -DskipTests
 
deploy:
 edge: true
 provider: cloudfoundry
 username: madhanswamy17@gmail.com
 password: sapphire.17
 api: https://api.run.pivotal.io
 organization: madhanswamy17-org
 space: development
on:
 repo: madhanvz1991/hackrace
