language: java

sudo: required

jdk:
 - oraclejdk8 
 
deploy:
 edge: true
 provider: cloudfoundry
 username: madhanswamy17@gmail.com
 password: sapphire.17
 api: https://api.run.pivotal.io
 organization: madhanswamy17-org
 space: development

