language: java

jdk:
  - openjdk8

sudo: required

all_branches: true

install: mvn clean install
 
deploy:
 edge: true
 provider: cloudfoundry
 username: madhanswamy17@gmail.com
 password: sapphire.17
 api: https://api.run.pivotal.io
 organization: madhanswamy17-org
 space: development
on:
 all_branches: true
 repo: madhanvz1991/hackrace
